Update `sol` save/load; add test
discsim/frank pull request #198
Opened 2023-03-01 17:38 UTC by jeffjennings

- `io.py`: Updates `pickle` calls to `dill`
- `tests.py`: Adds test for save/load of a sol from a standard and debris fit 

I ran into an issue saving/loading a sol object from a debris fit -- `pickle` was struggling to interpret `sol._vis_map._scale_height` as a function:

saving: `AttributeError: Can't pickle local object '<function>'`
loading: `OSError: Failed to interpret file '<path>_frank_sol.obj' as a pickle`

Replacing `pickle` with `dill` resolves this.

2023-03-01 17:40 UTC, rbooth200 commented
So _scale_height is a function, but it's probably ok to remove it from the visibility mapping object

2023-03-02 04:10 UTC, jeffjennings commented
Ok I implemented the power law in #195. This PR has very minor changes then, ready for review.

2023-03-02 09:26 UTC, rbooth200 requested changes
Can you add back the save/load test? It will catch problems with pickle should they arise again.

2023-03-02 15:21 UTC, jeffjennings commented
Sure, done in [3e79f22](https://github.com/discsim/frank/pull/198/commits/3e79f22506787f7ec04cf5b16e0ae884ada3a37c)

2023-03-02 17:55 UTC, rbooth200 approved these changes

2023-03-02 17:56 UTC, merged