Debris disc fitter, paper version
discsim/frank pull request #208
Opened 2023-07-03 19:18 UTC by rbooth200

This contains the code needed to update the debris disc fitter routines to the versions in the published paper. There are a few other changes in this branch unfortunately, but they are cosmetic or additional minor features, e.g. adding direct interpolation formulae to the Hankel transform.

2023-07-03 21:52 UTC, jeffjennings commented on frank/hankel.py
> +            raise ValueError("Space must be one of 'Real' or 'Fourier, not "
```suggestion
            raise ValueError("Space must be one of 'Real' or 'Fourier', not "
```

2023-07-03 21:53 UTC, jeffjennings commented on frank/statistical_models.py
> +import multiprocessing
```suggestion
# import multiprocessing
```

2023-07-03 21:55 UTC, jeffjennings requested changes
I've reviewed this, but you might want to look it over once more too.

2023-07-03 21:59 UTC, jeffjennings commented
Along with merging this, we could also delete the `debris` branch (it no longer has any commits ahead of `master`).

2023-07-04 07:43 UTC, rbooth200 commented
I accepted your changes and have checked over the code. Let me know if there is anything else. Otherwise, feel free to merge this and delete the debris* branches

2023-07-04 12:46 UTC, jeffjennings approved these changes

2023-07-04 12:46 UTC, merged